"""Cheating detection utilities."""

import re
from typing import Dict, List
import textstat


def calculate_readability(text: str) -> float:
    """
    Calculate Flesch Reading Ease score.
    
    Args:
        text: Input text
        
    Returns:
        Readability score (0-100, higher = easier to read)
    """
    if not text or len(text.strip()) < 10:
        return 0.0
    
    try:
        # For Russian text, use Flesch Reading Ease
        # Note: textstat may not be perfect for Russian, but gives a baseline
        score = textstat.flesch_reading_ease(text)
        return float(score)
    except Exception:
        return 0.0


def count_adjectives_and_adverbs(text: str) -> Dict[str, int]:
    """
    Count adjectives and adverbs in text.
    
    Args:
        text: Input text
        
    Returns:
        Dictionary with counts
    """
    try:
        import spacy
        
        # Try to load Russian model
        try:
            nlp = spacy.load("ru_core_news_sm")
        except OSError:
            # Fallback to English if Russian not available
            try:
                nlp = spacy.load("en_core_web_sm")
            except OSError:
                # If no models available, use simple regex
                return {
                    'adjectives': 0,
                    'adverbs': 0,
                    'total_words': len(text.split())
                }
        
        doc = nlp(text)
        adjectives = sum(1 for token in doc if token.pos_ == "ADJ")
        adverbs = sum(1 for token in doc if token.pos_ == "ADV")
        
        return {
            'adjectives': adjectives,
            'adverbs': adverbs,
            'total_words': len(doc)
        }
    except ImportError:
        # Fallback to simple word count
        words = text.split()
        return {
            'adjectives': 0,
            'adverbs': 0,
            'total_words': len(words)
        }
    except Exception:
        return {
            'adjectives': 0,
            'adverbs': 0,
            'total_words': len(text.split())
        }


def detect_special_characters(text: str) -> Dict[str, bool]:
    """
    Detect special characters (emojis, long dashes, etc.).
    
    Args:
        text: Input text
        
    Returns:
        Dictionary with detection results
    """
    # Emoji pattern
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"  # emoticons
        "\U0001F300-\U0001F5FF"  # symbols & pictographs
        "\U0001F680-\U0001F6FF"  # transport & map symbols
        "\U0001F1E0-\U0001F1FF"  # flags
        "\U00002702-\U000027B0"
        "\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE
    )
    
    has_emoji = bool(emoji_pattern.search(text))
    
    # Long dash (—)
    has_long_dash = '—' in text or '–' in text
    
    # Other special Unicode characters
    has_special_unicode = bool(re.search(r'[^\w\s\.,;:!?\-\(\)\[\]{}"\']', text))
    
    return {
        'has_emoji': has_emoji,
        'has_long_dash': has_long_dash,
        'has_special_unicode': has_special_unicode,
        'special_chars_count': len(re.findall(r'[^\w\s\.,;:!?\-\(\)\[\]{}"\']', text))
    }


def check_punctuation_errors(text: str) -> Dict[str, int]:
    """
    Check for basic punctuation errors.
    
    Args:
        text: Input text
        
    Returns:
        Dictionary with error counts
    """
    errors = {
        'missing_spaces_after_punctuation': 0,
        'double_spaces': 0,
        'missing_capitalization': 0
    }
    
    # Check for missing spaces after punctuation
    missing_spaces = len(re.findall(r'[.,;:!?][А-Яа-яA-Za-z]', text))
    errors['missing_spaces_after_punctuation'] = missing_spaces
    
    # Check for double spaces
    double_spaces = len(re.findall(r'  +', text))
    errors['double_spaces'] = double_spaces
    
    # Check for missing capitalization after sentence end
    # (simplified check)
    sentences = re.split(r'[.!?]\s+', text)
    missing_caps = sum(1 for s in sentences[1:] if s and not s[0].isupper())
    errors['missing_capitalization'] = missing_caps
    
    errors['total_errors'] = sum(errors.values())
    
    return errors


def detect_llm_likelihood(text: str) -> float:
    """
    Detect likelihood that text was generated by LLM.
    
    Uses heuristics:
    - Too structured (numbered lists, bullet points)
    - Repetitive phrases
    - Overly formal language
    
    Args:
        text: Input text
        
    Returns:
        Score from 0.0 to 1.0 (higher = more likely LLM-generated)
    """
    score = 0.0
    
    # Check for numbered lists (common in LLM responses)
    numbered_list_pattern = r'\d+[\.\)]\s+[А-Яа-яA-Z]'
    numbered_lists = len(re.findall(numbered_list_pattern, text))
    if numbered_lists > 3:
        score += 0.2
    
    # Check for bullet points
    bullet_points = text.count('•') + text.count('*') + text.count('-')
    if bullet_points > 5:
        score += 0.2
    
    # Check for repetitive phrases (common LLM patterns)
    llm_phrases = [
        'следует отметить',
        'необходимо отметить',
        'важно отметить',
        'стоит отметить',
        'можно отметить',
        'it should be noted',
        'it is important to',
        'it is necessary to'
    ]
    
    phrase_count = sum(1 for phrase in llm_phrases if phrase.lower() in text.lower())
    if phrase_count > 2:
        score += 0.3
    
    # Check for overly structured sections
    section_headers = len(re.findall(r'^[А-Яа-яA-Z][^.!?]{0,50}:', text, re.MULTILINE))
    if section_headers > 4:
        score += 0.2
    
    # Check for formal language patterns
    formal_patterns = [
        r'в\s+связи\s+с\s+тем',
        r'в\s+соответствии\s+с',
        r'с\s+учетом\s+того',
        'in accordance with',
        'with regard to'
    ]
    
    formal_count = sum(1 for pattern in formal_patterns if re.search(pattern, text, re.IGNORECASE))
    if formal_count > 2:
        score += 0.1
    
    return min(score, 1.0)


def analyze_cheating(text: str) -> Dict:
    """
    Comprehensive cheating detection analysis.
    
    Args:
        text: Input text
        
    Returns:
        Dictionary with all analysis results
    """
    readability = calculate_readability(text)
    pos_counts = count_adjectives_and_adverbs(text)
    special_chars = detect_special_characters(text)
    punctuation_errors = check_punctuation_errors(text)
    llm_likelihood = detect_llm_likelihood(text)
    
    return {
        'readability': readability,
        'adjectives_count': pos_counts.get('adjectives', 0),
        'adverbs_count': pos_counts.get('adverbs', 0),
        'total_words': pos_counts.get('total_words', 0),
        'special_chars': special_chars,
        'punctuation_errors': punctuation_errors,
        'llm_likelihood': llm_likelihood
    }
